config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#dashboard'

  get 'landing', to: 'static_pages#landing'

  resources :users, only: [:new, :create, :edit]
  resource :session, only: [:new, :create, :destroy]
  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index, :show, :update], path: '/players'
    resources :sports, only: [:index, :show]
    resources :games, only: [:index, :show, :create]
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  fname           :string(50)       not null
#  lname           :string(50)       not null
#  email           :string           not null
#  zipcode         :string(5)        not null
#  password_digest :string           not null
#  session_token   :string           not null
#  captain_id      :integer
#  player_id       :integer
#  elite           :boolean          default(FALSE), not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  img_url         :string
#  playing_area    :string
#  experience      :text
#

class User < ActiveRecord::Base
  include UserAuth

  has_many :player_sports, foreign_key: :player_id, dependent: :destroy
  has_many :sports, through: :player_sports, source: :sport

  has_many :games, dependent: :destroy
  has_many :players, through: :games, source: :players

  has_many :matches, foreign_key: :player_id
  has_many :joined_games, through: :matches, source: :game

  def self.search(sport_id)
    subquery = User.joins("JOIN player_sports ON player_sports.player_id = users.id")
      .joins("JOIN sports ON player_sports.sport_id = sports.id")
      .where("sports.id = ?", sport_id)

    self.from(subquery, :users).includes(:sports)
  end
end

app/controllers/api/users_controller.rb
module Api
  class UsersController < ApplicationController
    before_action :require_signed_in!
    wrap_parameters :user, {include: [:sport_ids, :playing_area, :experience]}

    def index
      limit = params[:limit].to_i
      if limit > 0
        @users = User.includes(:sports).where(zipcode: current_user.zipcode)
                     .where.not(id: current_user.id)
                     .sample(limit)
      elsif params[:sport_id]
        @users = User.where.not(id: current_user.id).includes(:sports).search(params[:sport_id])
      else
        @users = User.includes(:sports)
      end
    end

    def show
      @user = User.find(params[:id])
    end

    def update
      @user = current_user
      if @user.update(player_params)
        render json: @user
      else
        render json: @user.errors.fullmessages
      end
    end

    private
    def player_params
      params.require(:user).permit(:playing_area, :experience, sport_ids: [])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_signed_in!, except: [:new, :create]

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in!(@user)
        format.html { redirect_to root_path, notice: 'Successful sign up.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:fname, :lname, :email, :zipcode, :password)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li>
            <div class="alert alert-danger alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
              <%= message %>
            </div>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :fname, 'First name' %>
    <div>
      <%= f.text_field :fname, class: "form-control", autofocus: true %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :lname, 'Last name' %>
    <div>
      <%= f.text_field :lname, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <div>
      <%= f.text_field :email, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :zipcode %>
    <div>
      <%= f.text_field :zipcode, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :password %>
    <div>
      <%= f.password_field :password, class: "form-control" %>
    </div>
  </div>
  <div class="actions">
    <div>
      <%= f.submit 'Sign up', class: "col-xs-12 btn btn-default" %>
    </div>
  </div>
  <div>
      <%= link_to 'Already registered? Login.', new_session_path %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<div class="container user-auth">
  <div>
    <div class="form-container">
      <h3>WreckYourLeague</h3>
      <%= render 'form' %>
    </div>
  </div>
</div>