config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#dashboard'

  get 'landing', to: 'static_pages#landing'

  resources :users, only: [:new, :create, :edit]
  resource :session, only: [:new, :create, :destroy]
  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index, :show, :update], path: '/players'
    resources :sports, only: [:index, :show]
    resources :games, only: [:index, :show, :create]
  end
end

app/views/layouts/_header.html.erb
<div class="row">
  <%= render 'layouts/navgroup' %>
  <div class="jumbotron clearfix">
    <% unless ['users','sessions'].include?(params[:controller])  %>
      <% if signed_in? %>
        <h1>Welcome, <%= current_user.fname %></h1>
      <% else %>
        <h1>WreckYourLeague</h1> 
      <% end %>
    <% end  %>
  </div>
</div>
<h3>It's time to start winning.</h3>
<div class="gs-btn">
  <a href="#sports" id="sports-btn" class="btn btn-default">Get Started</a>
</div>

app/views/layouts/_navgroup.html.erb
<div class="btn-group" role="group" aria-label="..."> 
  <% if signed_in? %>
    <a href="#dashboard" class="btn btn-default">Dashboard</a>
    <a href="#account" class="btn btn-default">How it works</a>
    <%= link_to 'Sign out', session_path, class: "btn btn-default", method: :delete %>
  <% else %>
    <a href="<%= new_user_path %>" class="btn btn-default">Sign Up</a>
    <a href="#" class="btn btn-default">How it works</a>
    <a href="<%= new_session_path %>" class="btn btn-default">Login</a>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WreckYourLeague</title>
    <link rel="stylesheet" src="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.3/normalize.min.css" />
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <% if Rails.env.production? %>
      <% api_key = "key=AIzaSyDvf4AwOv908NkctdFlGcw8tKL_bXj65TM" %>
    <% else %>
      <% api_key = '' %>
    <% end %>
    <script type="text/javascript"
            src="https://maps.googleapis.com/maps/api/js?<%= api_key %>&libraries=drawing,geometry,places"></script>
  </head>
  <body>
    <%= yield %>
  </body>
</html>